### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by shawchip** [Gorzontrok/Bro-Maker#27]
I visited the Nexus mods website looking for some mods, and i found a satanbro one but it does not work, i am planning on fixing it but there are alot of files missing.
I wanted to ask if theres a way to check the broforce textures because i need a cutscene image of Satan
Also, i need help with pixel art

**Comment by alexneargarder** [comment]
I’m guessing the main file it’s missing is the mod file which was added in a BroMaker update that came out after it was released. You can check the wiki to see how they’re formatted: https://github.com/Gorzontrok/Bro-Maker/wiki/Creating-a-Mod-File

if you want to extract sprites from Broforce, I would recommend using a tool like Asset Studio: https://github.com/Perfare/AssetStudio/releases

For help with pixel art, and any further help on any other issues, I would recommend joining the FreeLives discord and posting in the bf-mods channel: https://discord.gg/freelives
