### ISSUE TITLE
Bug : "grenades" dont work

### ISSUE THREAD

**Issue by Golem2Fer** [Gorzontrok/Bro-Maker#3]
you want to give the "key" to change the grenades please 

("grenades" : "Martini")

**Comment by Gorzontrok** [comment]
The key is by default in all characters `"specialGrenade"`. I recommend to you place it in Awake.
I added example in the Wiki.

So it should look like this
```json
[...]
"beforeAwake": {
   "specialGrenade": "Martini"
},
[...]
```

**Comment by Gorzontrok** [comment]
Not an issue

**Comment by Golem2Fer** [comment]
> The key is by default in all characters `"specialGrenade"`. I recommend to you place it in Awake. I added example in the Wiki.
> 
> So it should look like this
> 
> ```json
> [...]
> "beforeAwake": {
>    "specialGrenade": "Martini"
> },
> [...]
> ```

Thank you👌
