### ISSUE TITLE
Help needed for own abilities

### ISSUE THREAD

**Issue by Golem2Fer** [Gorzontrok/Bro-Maker#4]
To do when you can but if possible make an example of construction of a special ability and how the integrated has a character thank you in advance otherwise congratulations for your very successful mod.

(i know is not a issue but i dont know where write for need help)

**Comment by Gorzontrok** [comment]
It is planned, because I'm making the ability core while making the abilities for Bronobi.

I set up a discussions tab to send messages without opening an issue.
But if you prefer messaging on Discord, you could either join the FreeLives Discord or add me.
